### ISSUE TITLE
Debug not Working "DEP1700" ITATKWinUI.build.appxrecipe missing

### ISSUE THREAD

**Issue by Constey** [nkasco/IT-Admin-Toolkit-WinUI#45]
Hi there,
i'm trying around with this project but i'm a bit stuck in debugging. I receive the following error when trying to build or debug:
![image](https://user-images.githubusercontent.com/11457386/226480110-18460817-cce2-4b2e-9b20-21ca0315f6fd.png)

`DEP1700: Die Rezeptdatei "C:\dev\IT-Admin-Toolkit-WinUI\bin\x64\Debug\net6.0-windows10.0.19041.0\ITATKWinUI.build.appxrecipe" ist nicht vorhanden. Möglicherweise müssen Sie Ihr Projekt erstellen.	`

While to public the app does work to get a runnable program, I don't know how to fix that message. May I can grap the recipe file somewhere or do I need to specify some more info somewhere?
Thanks very much,
Constantin

**Comment by Constey** [comment]
Just switching the Debug mode from Packaged to Unpackaged works like a charm :-)
![image](https://user-images.githubusercontent.com/11457386/226889594-b60e7ddd-02e5-4b45-b39a-f03e18e72876.png)

**Comment by nkasco** [comment]
This is the correct solution, it is stated in the ReadMe "Currently, this project is intended to be unpackaged if you are running the .sln from Visual Studio"

Glad you were able to get it working, looking forward to any contributions!
